### ISSUE TITLE
Upgrade to Scala 2.8.x

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#62]
At this time 2.8.0 is not out yet, but there is a 2.8.0.Beta1-RC2. Would be nice to support that on a separate scala-2.8 branch.

I tried to just change the POMs, but got compile errors:

<pre>
/Users/aslakhellesoy/scm/cuke4duke/cuke4duke/src/main/scala/cuke4duke/internal/scala/ScalaTransformations.scala:30: error: type mismatch;
 found   : scala.collection.immutable.Map[java.lang.Class[_],(String) => Option[_]]
 required: scala.collection.immutable.TreeMap[java.lang.Class[_],(String) => Option[_]]
      transformations = transformations.update(key, attempt(value))
</pre>

Not sure how to fix that.

**Comment by nirlaor** [comment]
here is our private solution to this compilation error (curtsy of ittayd):
<code>
implicit val classOrdering = new Ordering[Class[_]]{
      def compare(a: Class[_], b: Class[_]) = {
        if(a == b) 0
        else if(b.isAssignableFrom(a)) 1
        else -1
      }
    }
  private var transformations = new TreeMap[Class[_], String => Option[_]]()(classOrdering)
</code>
this works for this problem, but than the scala compiler fails with a stack overflow that i don't know how to handle.

**Comment by teigen** [comment]
the current codebase works with both 2.7 and 2.8, so I guess this one can be closed

**Comment by aslakhellesoy** [comment]
Closed!
